<?php

namespace Api\TaurusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BeneficiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaryRepository extends EntityRepository
{
   
}
