<?php

namespace Api\TaurusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function getUser($secretcode,$email) {
        return $this->getEntityManager()
                ->createQuery("SELECT a FROM ApiTaurusBundle:User a WHERE a.secretcode='" . $secretcode . "' AND a.email='" . $email . "'")
                ->getSingleResult();
    }
    
     public function getBankByUser($user) {
        return $this->getEntityManager()
                ->createQuery("SELECT b FROM ApiTaurusBundle:User a JOIN ApiTaurusBundle:Bank b WHERE a.id='" . $user->getId() . "' AND a.bank=b.id")
                ->getSingleResult();
    }
    
   
}
